In [80]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [81]:
from google.colab import files
uploaded = files.upload()

df = pd.read_csv(r'Raw_Data_HeartDisease.csv')

Saving Raw_Data_HeartDisease.csv to Raw_Data_HeartDisease.csv

In [82]:
print(df.head())

   age  sex  chest pain type  resting bp s  cholesterol  fasting blood sugar  \
0   40    1                2           140          289                    0
1   49    0                3           160          180                    0
2   37    1                2           130          283                    0
3   48    0                4           138          214                    0
4   54    1                3           150          195                    0

   resting ecg  max heart rate  exercise angina  oldpeak  ST slope  target
0            0             172                0      0.0         1       0
1            0             156                0      1.0         2       1
2            1              98                0      0.0         1       0
3            0             108                1      1.5         2       1
4            0             122                0      0.0         1       0

In [83]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1190 entries, 0 to 1189
Data columns (total 12 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   age                  1190 non-null   int64
 1   sex                  1190 non-null   int64
 2   chest pain type      1190 non-null   int64
 3   resting bp s         1190 non-null   int64
 4   cholesterol          1190 non-null   int64
 5   fasting blood sugar  1190 non-null   int64
 6   resting ecg          1190 non-null   int64
 7   max heart rate       1190 non-null   int64
 8   exercise angina      1190 non-null   int64
 9   oldpeak              1190 non-null   float64
 10  ST slope             1190 non-null   int64
 11  target               1190 non-null   int64
dtypes: float64(1), int64(11)
memory usage: 111.7 KB
None

In [84]:
## I don't Have any Null vlaue

In [85]:
print(df.describe())

               age          sex  chest pain type  resting bp s  cholesterol  \
count  1190.000000  1190.000000      1190.000000   1190.000000  1190.000000
mean     53.720168     0.763866         3.232773    132.153782   210.363866
std       9.358203     0.424884         0.935480     18.368823   101.420489
min      28.000000     0.000000         1.000000      0.000000     0.000000
25%      47.000000     1.000000         3.000000    120.000000   188.000000
50%      54.000000     1.000000         4.000000    130.000000   229.000000
75%      60.000000     1.000000         4.000000    140.000000   269.750000
max      77.000000     1.000000         4.000000    200.000000   603.000000

       fasting blood sugar  resting ecg  max heart rate  exercise angina  \
count          1190.000000  1190.000000     1190.000000      1190.000000
mean              0.213445     0.698319      139.732773         0.387395
std               0.409912     0.870359       25.517636         0.487360
min               0.000000     0.000000       60.000000         0.000000
25%               0.000000     0.000000      121.000000         0.000000
50%               0.000000     0.000000      140.500000         0.000000
75%               0.000000     2.000000      160.000000         1.000000
max               1.000000     2.000000      202.000000         1.000000

           oldpeak     ST slope       target
count  1190.000000  1190.000000  1190.000000
mean      0.922773     1.624370     0.528571
std       1.086337     0.610459     0.499393
min      -2.600000     0.000000     0.000000
25%       0.000000     1.000000     0.000000
50%       0.600000     2.000000     1.000000
75%       1.600000     2.000000     1.000000
max       6.200000     3.000000     1.000000

In [86]:
## max cholesterol of 603 and resting bp of 200 is not error outlier , it is a extreme outlier
## Medically possible but extremely high

dealing with Duplicates

In [87]:
df.duplicated().sum()

np.int64(272)

In [88]:
df = df.drop_duplicates()
df.duplicated().sum()

np.int64(0)

Dealing with Cholesterol Column

In [89]:
## cholesterol min value is zero , whyy (while mean is 210) ?? How manyy ??

zero_cholesterol = (df['cholesterol'] == 0).sum()
print (f"Total instances of cholesterol with zero value: {zero_cholesterol}")

Total instances of cholesterol with zero value: 172

In [90]:
## 172 zero will be a problem to visualize data.
## max cholesterol is 603 and min is 0 , if I take mean of the data it will shift upward , meaning mean will be too high because of few high number
## median will be better choice to replace it

In [91]:
## calculating median of only cholesterol columns and replacing with zero

median_cholesterol = df[df['cholesterol']>0]['cholesterol'].median()
df['cholesterol'] = df['cholesterol'].replace(0,median_cholesterol)
df['cholesterol'].describe()

count    918.000000
mean     243.204793
std       53.401297
min       85.000000
25%      214.000000
50%      237.000000
75%      267.000000
max      603.000000
Name: cholesterol, dtype: float64

Dealing with resting Bp s Column

In [92]:
## Data Set has minimun resting blood pressure 0, which is not possible in a living person

zero_resting_bp = (df['resting bp s']==0).sum()
print(f"Resting Bp with zero value: {zero_resting_bp}")

Resting Bp with zero value: 1

In [93]:
## I have 1 zero value
## max resitng bp is 200 which is medically possible and not a error outlier
## So I can take a mean and replace it because one replaced instance won't make big difference in visualisation unlike cholesterol (172 instances)

In [94]:
## replacing zero with mean
mean_resting_bp = df[df['resting bp s']>0]['resting bp s'].mean()
df['resting bp s'] = df['resting bp s'].replace(0, mean_resting_bp)

df['resting bp s'].describe()

count    918.000000
mean     132.540894
std       17.989932
min       80.000000
25%      120.000000
50%      130.000000
75%      140.000000
max      200.000000
Name: resting bp s, dtype: float64

Dealing with Oldpeak Column

In [95]:
## I also have old peak values in negative
## In dataset those negative values are considered rare clinical variants.

In [96]:
## total negative oldpeak value

negative_value_oldpeak = (df['oldpeak']<0).sum()
print(f"Total negative oldpeak records in dataset: {negative_value_oldpeak}")

Total negative oldpeak records in dataset: 13

In [97]:
df[df['oldpeak']<0].head(918)

,age,sex,chest pain type,resting bp s,cholesterol,fasting blood sugar,resting ecg,max heart rate,exercise angina,oldpeak,ST slope,target
322,63,1,4,100.0,237,1,0,109,0,-0.9,2,1
325,46,1,4,100.0,237,1,1,133,0,-2.6,2,1
326,42,1,4,105.0,237,1,0,128,1,-1.5,3,1
327,45,1,3,110.0,237,0,0,138,0,-0.1,1,0
332,56,1,4,115.0,237,1,1,82,0,-1.0,1,1
333,38,1,3,100.0,237,0,0,179,0,-1.1,1,0
335,51,1,4,130.0,237,1,0,170,0,-0.7,1,1
336,62,1,1,120.0,237,1,2,134,0,-0.8,2,1
353,56,1,4,120.0,237,0,1,100,1,-1.0,3,1
408,62,1,4,115.0,237,1,0,72,1,-0.5,2,1
414,56,1,3,125.0,237,1,0,98,0,-2.0,2,1
422,66,1,3,120.0,237,0,1,120,0,-0.5,1,0
513,35,1,3,123.0,161,0,1,153,0,-0.1,1,0

In [98]:
## most of the people with negative oldpeak have target 1 ( heart disease positive)
## Negative oldpeaks is pointing towards the problem. So I cannot make it 0
## Best way I can make it positive value

In [99]:
df['oldpeak'] = df['oldpeak'].abs()
df['oldpeak'].describe()

count    918.000000
mean       0.915251
std        1.042712
min        0.000000
25%        0.000000
50%        0.600000
75%        1.500000
max        6.200000
Name: oldpeak, dtype: float64

final Overview of the Dataset

In [100]:
df.describe()

,age,sex,chest pain type,resting bp s,cholesterol,fasting blood sugar,resting ecg,max heart rate,exercise angina,oldpeak,ST slope,target
count,918.000000,918.000000,918.000000,918.000000,918.000000,918.000000,918.000000,918.000000,918.000000,918.000000,918.000000,918.000000
mean,53.510893,0.789760,3.251634,132.540894,243.204793,0.233115,0.603486,136.809368,0.404139,0.915251,1.636166,0.553377
std,9.432617,0.407701,0.931031,17.989932,53.401297,0.423046,0.805968,25.460334,0.490992,1.042712,0.609341,0.497414
min,28.000000,0.000000,1.000000,80.000000,85.000000,0.000000,0.000000,60.000000,0.000000,0.000000,0.000000,0.000000
25%,47.000000,1.000000,3.000000,120.000000,214.000000,0.000000,0.000000,120.000000,0.000000,0.000000,1.000000,0.000000
50%,54.000000,1.000000,4.000000,130.000000,237.000000,0.000000,0.000000,138.000000,0.000000,0.600000,2.000000,1.000000
75%,60.000000,1.000000,4.000000,140.000000,267.000000,0.000000,1.000000,156.000000,1.000000,1.500000,2.000000,1.000000
max,77.000000,1.000000,4.000000,200.000000,603.000000,1.000000,2.000000,202.000000,1.000000,6.200000,3.000000,1.000000

Importing Cleaned Data to the Drive

In [102]:
from google.colab import drive
drive.mount('/content/drive')

# Save directly to a specific folder in your Drive
df.to_csv('/content/drive/My Drive/Cleaned_Data_HeartDisease.csv', index=False)

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).